[theme]
# Cor principal (botões, barra de progresso)
primaryColor = "#0C1C4C" 

# Cor de fundo principal da tela (Área da direita - Branco)
backgroundColor = "#FFFFFF" 

# Cor de fundo secundária (Barra Lateral - Azul escuro da JR)
secondaryBackgroundColor = "#0C1C4C" 

# Cor do texto principal (Área da direita)
textColor = "#0C1C4C" 

# Fonte
font = "sans serif"
